### ISSUE TITLE
2600hz/kamailio -> ERROR: connect_unix_sock

### ISSUE THREAD

**Issue by krull** [2600hz/docker#10]
@jamhed problem is [this part of run.sh](https://github.com/2600hz/docker/blob/master/kamailio/build/run.sh#L9), which produces the result:

```
kamailio@043afa606126:~$ sleep 5 && kamcmd dispatcher.reload
ERROR: connect_unix_sock: connect(/var/run/kamailio//kamailio_ctl): No such file or directory [2]
kamailio@043afa606126:~$
``` 

Hope this helps.

**Comment by fenollp** [comment]
Reproduced.

@jamhed See? adding `-e` finds stuff.

@krull Since this line appears to never have worked, it should be safe to remove it for now.
We will look deeper in this and decide what to do longer term.

Thanks!

**Comment by lazedo** [comment]
@fenollp @krull  this line doesn't make sense, it's maybe a leftover. you can't call `kamcmd` without kamailio running.

**Comment by krull** [comment]
@lazedo agreed.

I removed it on my local install and `2600hz/kamailio` worked.

But it is present in the docker image in [hub](https://hub.docker.com/r/2600hz/kamailio/) latest, so heads up guys.

Cheers

**Comment by fenollp** [comment]
@krull Can you send a PR our way?

**Comment by jamhed** [comment]
I believe this is resolved.
