### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by odannyc** [2600hz/docker#3]
The readme states:

> admin.sh gives access to the host inside the kazoo network. You need hosts file to access ui by http://kazoo-ui.kazoo and http://monster-ui.kazoo, and they, in turn, need to access http://kazoo.kazoo:8000, and you probably want to run UI on your host.

There is no `admin.sh` script.
Everytime I start all the containers I can't seem to access the monster-ui with it's url thats in the hosts file so I'm assuming it's because of that admin.sh script I need to run?

**Comment by voughtdq** [comment]
I think admin.sh is obsolete as `$THIS_REPOSITORY/kazoo/sup` seems to meet the same definition. What the second sentence is talking about is taking the output of the `host.sh` script and then appending it to `/etc/hosts` so you can access the docker images. 

Monster ui should be accessible at monster-ui.kazoo:3000

**Comment by jamhed** [comment]
Thanks, @voughtdq.
