### ISSUE TITLE
'network' is not a docker command

### ISSUE THREAD

**Issue by mickaelmonsieur** [2600hz/docker#7]
Hi,
I try to deploy kazoo with docker and i have this error:

`root@sw1003:/home/test/docker# ./run.sh
starting network: kazoo docker: 'network' is not a docker command. See 'docker --help'.
starting: rabbitmq.kazoo docker: Conflicting options: -h and the network mode (--net). See 'docker run --help'.
starting: couchdb.kazoo docker: Conflicting options: -h and the network mode (--net). See 'docker run --help'.
starting: kazoo.kazoo docker: Conflicting options: -h and the network mode (--net). See 'docker run --help'.
starting: kamailio.kazoo docker: Conflicting options: -h and the network mode (--net). See 'docker run --help'.
starting: freeswitch.kazoo docker: Conflicting options: -h and the network mode (--net). See 'docker run --help'.
adding dispatcher freeswitch.kazoo to kamailio kamailio.kazoo FATA[0000] Error response from daemon: no such id: kamailio.kazoo 
starting: monster-ui.kazoo docker: Conflicting options: -h and the network mode (--net). See 'docker run --help'.`

Debian 8.7

docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

Thanks for your help

**Comment by mickaelmonsieur** [comment]
Hello,

Apparently, docker 1.6 is too old, but how to know, the minimum version required by kazoo is not indicated.
With docker 1.13.0, I have this after the run:

`docker ps
CONTAINER ID        IMAGE               COMMAND                   CREATED             STATUS              PORTS                                NAMES
4c5f208fa395        kazoo/monster-ui    "/bin/sh -c \"build..."   31 minutes ago      Up 31 minutes                                            monster-ui.kazoo
2c406c3f2658        kazoo/freeswitch    "./run.sh"                31 minutes ago      Up 31 minutes                                            freeswitch.kazoo
cf1e7d43cbb6        kazoo/kamailio      "./run.sh"                31 minutes ago      Up 31 minutes                                            kamailio.kazoo
f35b1d9fcc30        kazoo/kazoo         "/bin/sh -c ./run.sh"     31 minutes ago      Up 31 minutes                                            kazoo.kazoo
43f17a435245        kazoo/couchdb       "tini -- /docker-e..."    31 minutes ago      Up 31 minutes                                            couchdb.kazoo
1d21ba6b285e        kazoo/rabbitmq      "/docker-entrypoin..."    31 minutes ago      Up 31 minutes       4369/tcp, 5671-5672/tcp, 25672/tcp   rabbitmq.kazoo`

but:
`./hosts.sh >> /etc/hosts
Error: No such object: makebusy.kazoo
Error: No such object: makebusy-fs-auth.kazoo
Error: No such object: makebusy-fs-pbx.kazoo
Error: No such object: makebusy-fs-carrier.kazoo`

Normal?

**Comment by jamhed** [comment]
> Normal?

Sort of. I'll update it to skip missing containers.

**Comment by jamhed** [comment]
https://github.com/2600hz/docker/commit/d4d18505ccc5965556fde3bcf04510a15100a975

**Comment by jamhed** [comment]
@mickaelmonsieur Also I've updated README.md and build.sh to indicate and check minimal Docker version required.
